package com.pingok.vocational.domain.primaryCar;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 车辆轨迹信息表(TBL_VEHICLE_TRAIL_INFO)
 * 
 * @author bianj
 * @version 1.0.0 2022-12-12
 */
@Data
@Table(name = "TBL_VEHICLE_TRAIL_INFO")
public class TblVehicleTrailInfo implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4775468108794816450L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private BigDecimal id;

    /** 车牌号 */
    private String license;

    /** 车牌颜色 */
    private BigDecimal color;

    /** 原始经度 */
    private BigDecimal lon;

    /** 原始纬度 */
    private BigDecimal lat;

    /** gps时间 */
    private Date time;

    /** gps速度 */
    private BigDecimal speed;

    /** 方向 */
    private BigDecimal direction;

    /** 高度（海拔） */
    private BigDecimal altitude;

    /** acc状态,0关 1开 */
    private BigDecimal acc;

}