package com.pingok.vocational.domain.primaryCar;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 运单信息表(TBL_WAYBILL_INFO)
 * 
 * @author bianj
 * @version 1.0.0 2022-12-12
 */
@Data
@Table(name = "TBL_WAY_BILL_INFO")
public class TblWaybillInfo implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -4509545740529301590L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private BigDecimal id;

    /** 结论 */
    private String accidentConclusion;

    /** 事故企业名称 */
    private String accidentCorpName;

    /** 后果 */
    private String accidentConsequence;

    /** 事故驾驶员从业姓名 */
    private String accidentDriverName;

    /** 事故驾驶员资格证号 */
    private String accidentDriverSerialNumber;

    /** 事故押运员从业姓名 */
    private String accidentEscortName;

    /** 事故押运员资格证号 */
    private String accidentEscortSerialNumber;

    /** 事故经过 */
    private String accidentGoThrough;

    /** 事故地点 */
    private String accidentLocation;

    /** 事故时间 */
    private Date accidentTime;

    /** 事故车辆号 */
    private String accidentVehicleLicense;

    /** 年审有效期 */
    private Date annualReviewDate;

    /** 车辆信息-有效开始时间 */
    private Date beginValidDate;

    /** 公司信息-公司名称 */
    private String cnName;

    /** 驾驶员信息-身份证号 */
    private String driverIdentification;

    /** 驾驶员信息-姓名 */
    private String driverName;

    /** 驾驶员信息-电话 */
    private String driverPhone;

    /** 驾驶员信息-从业资格证号 */
    private String driverSerialNumber;

    /** 驾驶员信息-从业类别 */
    private String driverType;

    /** 目的地 */
    private String endPoint;

    /** 押运员-身份证号 */
    private String escortIdentification;

    /** 押运员-姓名 */
    private String escortName;

    /** 押运员-电话 */
    private String escortPhone;

    /** 押运员-从业资格证号 */
    private String escortSerialNumber;

    /** 押运员-从业类别 */
    private String escortType;

    /** 货物信息-危险等级 */
    private String goodsLevel;

    /** 货物信息-联合国编号 */
    private String goodsNumber;

    /** 货物信息-启运地 */
    private String goodsStartAddress;

    /** 货物信息-品名类别 */
    private String goodsType;

    /** 货物信息-货重 */
    private BigDecimal goodsWeight;

    /** 公司信息-法定代表人 */
    private String legalPersonName;

    /** 公司信息-法定代表人联系电话 */
    private String legalPersonPhone;

    /** 承运人责任险有效日期 */
    private Date liabilityInsuranceDate;

    /** 公司信息-许可证号 */
    private String licenseNumber;

    /** 公司信息-经营地址 */
    private String operateAddress;

    /** 运输车辆综合性能和等级评定有效期 */
    private Date ratingDate;

    /** 公司信息-企业安全负责人名称 */
    private String safePersonName;

    /** 公司信息-企业安全负责人联系电话 */
    private String safePersonPhone;

    /** 车辆信息-车辆技术等级 */
    private String technicalGrade;

    /** 车辆信息-车辆技术等级日期 */
    private Date technicalGradeDate;

    /** 车辆信息-车辆总质量 */
    private BigDecimal vehicleGrossMass;

    /** 车辆信息-车牌号 */
    private String vehicleLicense;

    /** 车辆信息-道路运输证号 */
    private String vehicleLicenseNumber;

    /** 车辆信息-管理机构 */
    private String vehicleManagerAgence;

    /** 车辆信息-车辆经营范围（牵引车） */
    private String vehicleScope;

    /** 车辆信息-车辆状态 */
    private BigDecimal vehicleStatus;

    /** 车辆信息-车辆类型 */
    private BigDecimal vehicleType;

}