package com.pingok.monitor.domain.device;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * 信息发布记录表(TBL_RELEASE_RECORD)
 * 
 * @author xia
 * @version 1.0.0 2022-06-15
 */
@Data
@Table(name = "TBL_RELEASE_RECORD")
public class TblReleaseRecord implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3296406038368099028L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private Long id;

    /** 设备编码 */
    private String deviceId;

    /** 设备名称 */
    private String deviceName;

    /** 桩号 */
    private String pileNo;

    /** 信息类型 */
    private Integer infoType;

    /** 预设信息 */
    private String presetInfo;

    /** 内容字体 */
    private String typeface;

    /** 字体大小 */
    private Integer typefaceSize;

    /** 字体颜色 */
    private String color;

    /** 图片类别 */
    private Integer pictureType;

    /** 发布时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date presetTime;

    /** 撤销时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date revokeTime;

    /** 发布用户ID */
    private Long presetUserId;

    /** 撤销用户ID */
    private Long revokeUserId;

    /** 预设名称 */
    private String presetName;

}