package com.pingok.datacenter.domain.rush;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.models.auth.In;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 闯关记录表(TBL_RUSH_RECORD)
 * 
 * @author bianj
 * @version 1.0.0 2022-09-16
 */
@Data
@Table(name = "TBL_RUSH_RECORD")
public class TblRushRecord implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1061437861168078311L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private Long id;

    /** 车牌 */
    private String vehPlate;

    /** 车牌颜色 */
    private Integer vehColor;

    /** 识别时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date transTime;

    /** 车道Node十六进制 */
    private String laneHex;

    /** 车道名称 */
    private String laneName;

    /** 车道名称（圈圈号) */
    private String markName;

    /** 收费站名称 */
    private String stationName;

    /** 收费站Node十六进制 */
    private String stationHex;

    /** 状态  0 新增 1确认 2误报 */
    private Integer status;

    /** 确认时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date confirmTime;

    /** 可信度 */
    private BigDecimal reliability;

    /** 确认人ID */
    private Long confirmUserId;

    @Transient
    private String confirmUser;

    @Transient
    private String vehColorDesc;

}