package com.pingok.vocational.domain.maintenance;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 养护车辆GPS信息表(TBL_MAINTAIN_CAR_GPS)
 * 
 * @author xia
 * @version 1.0.0 2022-06-15
 */
@Table(name = "TBL_MAINTAIN_CAR_GPS")
public class TblMaintainCarGps implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -1L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private Long id;

    /** 车牌 */
    private String licensePlate;

    /** 坐标 */
    private String coordinates;

    /** 时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date time;

    /** 位置描述 */
    private String reverseGeocode;

    /** 车速 */
    private BigDecimal speed;

    /** 创建时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /** 更新时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取车牌
     * 
     * @return 车牌
     */
    public String getLicensePlate() {
        return this.licensePlate;
    }

    /**
     * 设置车牌
     * 
     * @param licensePlate
     *          车牌
     */
    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate;
    }

    /**
     * 获取坐标
     * 
     * @return 坐标
     */
    public String getCoordinates() {
        return this.coordinates;
    }

    /**
     * 设置坐标
     * 
     * @param coordinates
     *          坐标
     */
    public void setCoordinates(String coordinates) {
        this.coordinates = coordinates;
    }

    /**
     * 获取时间
     * 
     * @return 时间
     */
    public Date getTime() {
        return this.time;
    }

    /**
     * 设置时间
     * 
     * @param time
     *          时间
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * 获取位置描述
     * 
     * @return 位置描述
     */
    public String getReverseGeocode() {
        return this.reverseGeocode;
    }

    /**
     * 设置位置描述
     * 
     * @param reverseGeocode
     *          位置描述
     */
    public void setReverseGeocode(String reverseGeocode) {
        this.reverseGeocode = reverseGeocode;
    }

    /**
     * 获取车速
     * 
     * @return 车速
     */
    public BigDecimal getSpeed() {
        return this.speed;
    }

    /**
     * 设置车速
     * 
     * @param speed
     *          车速
     */
    public void setSpeed(BigDecimal speed) {
        this.speed = speed;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取更新时间
     * 
     * @return 更新时间
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置更新时间
     * 
     * @param updateTime
     *          更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}