package com.pingok.datacenter.domain.roster.green;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * TBL_GREEN_VERSION
 * 
 * @author bianj
 * @version 1.0.0 2022-10-25
 */
@Data
@Table(name = "TBL_GREEN_VERSION")
public class TblGreenVersion implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7266783684235555098L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private Long id;

    /** 版本号 */
    private String version;
}