package com.pingok.event.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * 事件处置记录表(TBL_EVENT_HANDLE)
 *
 * @author qiumin
 * @version 1.0.0 2022-04-03
 */
@Data
@Table(name = "TBL_EVENT_HANDLE")
public class TblEventHandle implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = 1982825010851790253L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * id
     */
    @Id
    private Long id;

    /**
     * 事件ID
     */
    private Long eventId;

    /**
     * 处置类型：0-人工填报 4-可变信息标志推送  5-可变限速标志推送  6-ETC门架车路协同  7-超视距诱导灯  8-高德地图  9-应急资源 10-百度地图
     */
    private Integer type;

    /**
     * 处置内容
     */
    private String handleContent;

    /**
     * 处置人id
     */
    private Long userId;

    /**
     * 处置时间
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date handleTime;

    /**
     * 创建时间
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

}