package com.pingok.event.domain;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * TBL_EVENT_ALARM
 *
 * @author bianj
 * @version 1.0.0 2022-10-08
 */
@Data
@Table(name = "TBL_EVENT_ALARM")
public class TblEventAlarm implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = -3953426434681626761L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * id
     */
    @Id
    private Long id;

    /**
     * 事件类型
     */
    @ApiModelProperty(value = "事件类型")
    private Integer eventType;

}