package com.pingok.vocational.domain.pursues;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 追讨门架流水表(TBL_PURSUES_GANTRY)
 * 
 * @author xia
 * @version 1.0.0 2022-06-30
 */
@Table(name = "TBL_PURSUES_GANTRY")
public class TblPursuesGantry implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5883627569343859372L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private Long id;

    /** 协调ID */
    private String concertId;

    /** 车牌号码+间隔符+车牌颜色\r\n            车牌颜色2位数字:\r\n            0-蓝色，1-黄色，\r\n            2-黑色，3-白色，\r\n            4- 渐变绿色\r\n            5- 黄绿双拼色\r\n            6- 蓝白渐变色\r\n            7- 临时牌照\r\n            9- 未确定\r\n            11-绿色\r\n            12-红色\r\n            例：京A12345_1\r\n            ETC交易实际车牌不做车牌格式校验\r\n             */
    private String vehiclePlate;

    /** 1-一型客车\r\n            2-二型客车\r\n            3-三型客车\r\n            4-四型客车\r\n            11-一型货车\r\n            12-二型货车\r\n            13-三型货车\r\n            14-四型货车\r\n            15-五型货车\r\n            16-六型货车\r\n            21-一型专项作业车\r\n            22-二型专项作业车\r\n            23-三型专项作业车\r\n            24-四型专项作业车\r\n            25-五型专项作业车\r\n            26-六型专项作业车\r\n             */
    private BigDecimal vehicleType;

    /** 门架编号 */
    private String gantryId;

    /** 1-OBU（单片式、双片式）\r\n            2-CPC卡\r\n             */
    private BigDecimal mediaType;

    /** OBU/CPC 序号编码 */
    private String obuSn;

    /** 车牌图像 */
    private String licenseImage;

    /** YYYY-MM-DDTHH:mm:ss */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date transTime;

    /** 交易金额 */
    private BigDecimal fee;

    /** 应收金额 */
    private BigDecimal payFee;

    /** 优惠金额 */
    private BigDecimal discountFee;

    /** 卡面扣费金额 */
    private BigDecimal transFee;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键
     * 
     * @return 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置主键
     * 
     * @param id
     *          主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取协调ID
     * 
     * @return 协调ID
     */
    public String getConcertId() {
        return this.concertId;
    }

    /**
     * 设置协调ID
     * 
     * @param concertId
     *          协调ID
     */
    public void setConcertId(String concertId) {
        this.concertId = concertId;
    }

    /**
     * 获取车牌号码+间隔符+车牌颜色\r\n            车牌颜色2位数字:\r\n            0-蓝色，1-黄色，\r\n            2-黑色，3-白色，\r\n            4- 渐变绿色\r\n            5- 黄绿双拼色\r\n            6- 蓝白渐变色\r\n            7- 临时牌照\r\n            9- 未确定\r\n            11-绿色\r\n            12-红色\r\n            例：京A12345_1\r\n            ETC交易实际车牌不做车牌格式校验\r\n            
     * 
     * @return 车牌号码+间隔符+车牌颜色\r\n            车牌颜色2位数字
     */
    public String getVehiclePlate() {
        return this.vehiclePlate;
    }

    /**
     * 设置车牌号码+间隔符+车牌颜色\r\n            车牌颜色2位数字:\r\n            0-蓝色，1-黄色，\r\n            2-黑色，3-白色，\r\n            4- 渐变绿色\r\n            5- 黄绿双拼色\r\n            6- 蓝白渐变色\r\n            7- 临时牌照\r\n            9- 未确定\r\n            11-绿色\r\n            12-红色\r\n            例：京A12345_1\r\n            ETC交易实际车牌不做车牌格式校验\r\n            
     * 
     * @param vehiclePlate
     *          车牌号码+间隔符+车牌颜色\r\n            车牌颜色2位数字
     */
    public void setVehiclePlate(String vehiclePlate) {
        this.vehiclePlate = vehiclePlate;
    }

    /**
     * 获取1-一型客车\r\n            2-二型客车\r\n            3-三型客车\r\n            4-四型客车\r\n            11-一型货车\r\n            12-二型货车\r\n            13-三型货车\r\n            14-四型货车\r\n            15-五型货车\r\n            16-六型货车\r\n            21-一型专项作业车\r\n            22-二型专项作业车\r\n            23-三型专项作业车\r\n            24-四型专项作业车\r\n            25-五型专项作业车\r\n            26-六型专项作业车\r\n            
     * 
     * @return 1-一型客车\r\n            2-二型客车\r\n            3-三型客车\r\n            4-四型客车\r\n            11-一型货车\r\n            12-二型货车\r\n            13-三型货车\r\n            14-四型货车\r\n            15-五型货车\r\n            16-六型货车\r\n            21-一型专项作业车\r\n            22-二型专项作业车\r\n            23-三型专项作业车\r\n            24-四型专项作业车\r\n            25-五型专项作业车\r\n            26-六型专项作业车\r\n            
     */
    public BigDecimal getVehicleType() {
        return this.vehicleType;
    }

    /**
     * 设置1-一型客车\r\n            2-二型客车\r\n            3-三型客车\r\n            4-四型客车\r\n            11-一型货车\r\n            12-二型货车\r\n            13-三型货车\r\n            14-四型货车\r\n            15-五型货车\r\n            16-六型货车\r\n            21-一型专项作业车\r\n            22-二型专项作业车\r\n            23-三型专项作业车\r\n            24-四型专项作业车\r\n            25-五型专项作业车\r\n            26-六型专项作业车\r\n            
     * 
     * @param vehicleType
     *          1-一型客车\r\n            2-二型客车\r\n            3-三型客车\r\n            4-四型客车\r\n            11-一型货车\r\n            12-二型货车\r\n            13-三型货车\r\n            14-四型货车\r\n            15-五型货车\r\n            16-六型货车\r\n            21-一型专项作业车\r\n            22-二型专项作业车\r\n            23-三型专项作业车\r\n            24-四型专项作业车\r\n            25-五型专项作业车\r\n            26-六型专项作业车\r\n            
     */
    public void setVehicleType(BigDecimal vehicleType) {
        this.vehicleType = vehicleType;
    }

    /**
     * 获取门架编号
     * 
     * @return 门架编号
     */
    public String getGantryId() {
        return this.gantryId;
    }

    /**
     * 设置门架编号
     * 
     * @param gantryId
     *          门架编号
     */
    public void setGantryId(String gantryId) {
        this.gantryId = gantryId;
    }

    /**
     * 获取1-OBU（单片式、双片式）\r\n            2-CPC卡\r\n            
     * 
     * @return 1-OBU
     */
    public BigDecimal getMediaType() {
        return this.mediaType;
    }

    /**
     * 设置1-OBU（单片式、双片式）\r\n            2-CPC卡\r\n            
     * 
     * @param mediaType
     *          1-OBU
     */
    public void setMediaType(BigDecimal mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * 获取OBU/CPC 序号编码
     * 
     * @return OBU/CPC 序号编码
     */
    public String getObuSn() {
        return this.obuSn;
    }

    /**
     * 设置OBU/CPC 序号编码
     * 
     * @param obuSn
     *          OBU/CPC 序号编码
     */
    public void setObuSn(String obuSn) {
        this.obuSn = obuSn;
    }

    /**
     * 获取车牌图像
     * 
     * @return 车牌图像
     */
    public String getLicenseImage() {
        return this.licenseImage;
    }

    /**
     * 设置车牌图像
     * 
     * @param licenseImage
     *          车牌图像
     */
    public void setLicenseImage(String licenseImage) {
        this.licenseImage = licenseImage;
    }

    /**
     * 获取YYYY-MM-DDTHH:mm:ss
     * 
     * @return YYYY-MM-DDTHH
     */
    public Date getTransTime() {
        return this.transTime;
    }

    /**
     * 设置YYYY-MM-DDTHH:mm:ss
     * 
     * @param transTime
     *          YYYY-MM-DDTHH
     */
    public void setTransTime(Date transTime) {
        this.transTime = transTime;
    }

    /**
     * 获取交易金额
     * 
     * @return 交易金额
     */
    public BigDecimal getFee() {
        return this.fee;
    }

    /**
     * 设置交易金额
     * 
     * @param fee
     *          交易金额
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * 获取应收金额
     * 
     * @return 应收金额
     */
    public BigDecimal getPayFee() {
        return this.payFee;
    }

    /**
     * 设置应收金额
     * 
     * @param payFee
     *          应收金额
     */
    public void setPayFee(BigDecimal payFee) {
        this.payFee = payFee;
    }

    /**
     * 获取优惠金额
     * 
     * @return 优惠金额
     */
    public BigDecimal getDiscountFee() {
        return this.discountFee;
    }

    /**
     * 设置优惠金额
     * 
     * @param discountFee
     *          优惠金额
     */
    public void setDiscountFee(BigDecimal discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * 获取卡面扣费金额
     * 
     * @return 卡面扣费金额
     */
    public BigDecimal getTransFee() {
        return this.transFee;
    }

    /**
     * 设置卡面扣费金额
     * 
     * @param transFee
     *          卡面扣费金额
     */
    public void setTransFee(BigDecimal transFee) {
        this.transFee = transFee;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}