package com.pingok.vocational.domain.pursues;

import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 追讨车道牌识流水表(TBL_PURSUES_LPR)
 * 
 * @author xia
 * @version 1.0.0 2022-07-05
 */
@Table(name = "TBL_PURSUES_LPR")
public class TblPursuesLpr implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -125909568184095611L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private Long id;

    /** 协调ID */
    private String concertId;

    /** 车牌 */
    private String vehPlate;

    /** 通过时间 */
    private Date transTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键
     * 
     * @return 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置主键
     * 
     * @param id
     *          主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取协调ID
     * 
     * @return 协调ID
     */
    public String getConcertId() {
        return this.concertId;
    }

    /**
     * 设置协调ID
     * 
     * @param concertId
     *          协调ID
     */
    public void setConcertId(String concertId) {
        this.concertId = concertId;
    }

    /**
     * 获取车牌
     * 
     * @return 车牌
     */
    public String getVehPlate() {
        return this.vehPlate;
    }

    /**
     * 设置车牌
     * 
     * @param vehPlate
     *          车牌
     */
    public void setVehPlate(String vehPlate) {
        this.vehPlate = vehPlate;
    }

    /**
     * 获取通过时间
     * 
     * @return 通过时间
     */
    public Date getTransTime() {
        return this.transTime;
    }

    /**
     * 设置通过时间
     * 
     * @param transTime
     *          通过时间
     */
    public void setTransTime(Date transTime) {
        this.transTime = transTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}