package com.pingok.vocational.domain.pursues;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 追讨出入口流水表(TBL_PURSUES_TRANS)
 * 
 * @author xia
 * @version 1.0.0 2022-06-30
 */
@Table(name = "TBL_PURSUES_TRANS")
public class TblPursuesTrans implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -804607768183237127L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private Long id;

    /** 协调ID */
    private String concertId;

    /** 入口车牌 */
    private String enVehPlate;

    /** 入口车牌颜色 2 位数字:  0-蓝色，1-黄色， 2-黑色，3-白色， 4- 渐变绿色 5- 黄绿双拼色 6- 蓝白渐变色 7- 临时牌照 11-绿色 12-红色 */
    private BigDecimal enVehColor;

    /** 入口车型 1-4：1~4型客车 11-16：1~6型货车  21-26 1~6型专项作业车 */
    private BigDecimal enVehClass;

    /** 入口车道Node十六进制码 */
    private String enLaneHex;

    /** 入口时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date enTransTime;

    /** 入口通行介质 5 ETC通行，6 CPC卡，9 纸券 */
    private Integer enPassType;

    /** 入口CPC/ETC卡ID */
    private String enCardId;

    /** 入口车情 0-普通  8-军警 10-紧急  14-车队 （35号公告已定义）21-绿通车 22-联合收割机 23-抢险救灾 24-Jl类型集装箱 25-大件运输；26-应急车27-货车列车或半挂汽车列车 28- J2类型集装箱 90-放行车 91-闯关车 */
    private BigDecimal enVehStatus;

    /** 入口牌识图片 */
    private String enImage;

    /** 出口车道Node十六进制码 */
    private String exLaneHex;

    /** 出口车牌 */
    private String exVehPlate;

    /** 出口时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date exTransTime;

    /** 出口通行介质 5 ETC通行，6 CPC卡，9 纸券 */
    private Integer exPassType;

    /** 出口CPC/ETC卡ID */
    private String exCardId;

    /** 出口车情 0-普通  8-军警 10-紧急  14-车队 （35号公告已定义）21-绿通车 22-联合收割机 23-抢险救灾 24-Jl类型集装箱 25-大件运输；26-应急车27-货车列车或半挂汽车列车 28- J2类型集装箱 90-放行车 91-闯关车 */
    private Integer exVehStatus;

    /** 出口牌识图片 */
    private String exImage;

    /** 计费方式 1-按OBU内累计优惠后金额计费   2-按OBU内累计优惠前金额计费（废弃） 3-按CPC卡内累计金额计费  4-省中心在线服务计费5-部中心在线服务计费  6-按全网最小费额计费  11-开放式计费 */
    private BigDecimal feeType;

    /** 总金额 */
    private BigDecimal tollFee;

    /** 本省金额 */
    private BigDecimal localFee;

    /** 交易金额 */
    private BigDecimal amount;


    private String enGid;

    private String exGid;

    private String passId;
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键
     * 
     * @return 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置主键
     * 
     * @param id
     *          主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取协调ID
     * 
     * @return 协调ID
     */
    public String getConcertId() {
        return this.concertId;
    }

    /**
     * 设置协调ID
     * 
     * @param concertId
     *          协调ID
     */
    public void setConcertId(String concertId) {
        this.concertId = concertId;
    }

    /**
     * 获取入口车牌
     * 
     * @return 入口车牌
     */
    public String getEnVehPlate() {
        return this.enVehPlate;
    }

    /**
     * 设置入口车牌
     * 
     * @param enVehPlate
     *          入口车牌
     */
    public void setEnVehPlate(String enVehPlate) {
        this.enVehPlate = enVehPlate;
    }

    /**
     * 获取入口车牌颜色 2 位数字:  0-蓝色，1-黄色， 2-黑色，3-白色， 4- 渐变绿色 5- 黄绿双拼色 6- 蓝白渐变色 7- 临时牌照 11-绿色 12-红色
     * 
     * @return 入口车牌颜色 2 位数字
     */
    public BigDecimal getEnVehColor() {
        return this.enVehColor;
    }

    /**
     * 设置入口车牌颜色 2 位数字:  0-蓝色，1-黄色， 2-黑色，3-白色， 4- 渐变绿色 5- 黄绿双拼色 6- 蓝白渐变色 7- 临时牌照 11-绿色 12-红色
     * 
     * @param enVehColor
     *          入口车牌颜色 2 位数字
     */
    public void setEnVehColor(BigDecimal enVehColor) {
        this.enVehColor = enVehColor;
    }

    /**
     * 获取入口车型 1-4：1~4型客车 11-16：1~6型货车  21-26 1~6型专项作业车
     * 
     * @return 入口车型 1-4
     */
    public BigDecimal getEnVehClass() {
        return this.enVehClass;
    }

    /**
     * 设置入口车型 1-4：1~4型客车 11-16：1~6型货车  21-26 1~6型专项作业车
     * 
     * @param enVehClass
     *          入口车型 1-4
     */
    public void setEnVehClass(BigDecimal enVehClass) {
        this.enVehClass = enVehClass;
    }

    /**
     * 获取入口车道Node十六进制码
     * 
     * @return 入口车道Node十六进制码
     */
    public String getEnLaneHex() {
        return this.enLaneHex;
    }

    /**
     * 设置入口车道Node十六进制码
     * 
     * @param enLaneHex
     *          入口车道Node十六进制码
     */
    public void setEnLaneHex(String enLaneHex) {
        this.enLaneHex = enLaneHex;
    }

    /**
     * 获取入口时间
     * 
     * @return 入口时间
     */
    public Date getEnTransTime() {
        return this.enTransTime;
    }

    /**
     * 设置入口时间
     * 
     * @param enTransTime
     *          入口时间
     */
    public void setEnTransTime(Date enTransTime) {
        this.enTransTime = enTransTime;
    }

    /**
     * 获取入口通行介质 5 ETC通行，6 CPC卡，9 纸券
     * 
     * @return 入口通行介质 5 ETC通行
     */
    public Integer getEnPassType() {
        return this.enPassType;
    }

    /**
     * 设置入口通行介质 5 ETC通行，6 CPC卡，9 纸券
     * 
     * @param enPassType
     *          入口通行介质 5 ETC通行
     */
    public void setEnPassType(Integer enPassType) {
        this.enPassType = enPassType;
    }

    /**
     * 获取入口CPC/ETC卡ID
     * 
     * @return 入口CPC/ETC卡ID
     */
    public String getEnCardId() {
        return this.enCardId;
    }

    /**
     * 设置入口CPC/ETC卡ID
     * 
     * @param enCardId
     *          入口CPC/ETC卡ID
     */
    public void setEnCardId(String enCardId) {
        this.enCardId = enCardId;
    }

    /**
     * 获取入口车情 0-普通  8-军警 10-紧急  14-车队 （35号公告已定义）21-绿通车 22-联合收割机 23-抢险救灾 24-Jl类型集装箱 25-大件运输；26-应急车27-货车列车或半挂汽车列车 28- J2类型集装箱 90-放行车 91-闯关车
     * 
     * @return 入口车情 0-普通  8-军警 10-紧急  14-车队 
     */
    public BigDecimal getEnVehStatus() {
        return this.enVehStatus;
    }

    /**
     * 设置入口车情 0-普通  8-军警 10-紧急  14-车队 （35号公告已定义）21-绿通车 22-联合收割机 23-抢险救灾 24-Jl类型集装箱 25-大件运输；26-应急车27-货车列车或半挂汽车列车 28- J2类型集装箱 90-放行车 91-闯关车
     * 
     * @param enVehStatus
     *          入口车情 0-普通  8-军警 10-紧急  14-车队 
     */
    public void setEnVehStatus(BigDecimal enVehStatus) {
        this.enVehStatus = enVehStatus;
    }

    /**
     * 获取入口牌识图片
     * 
     * @return 入口牌识图片
     */
    public String getEnImage() {
        return this.enImage;
    }

    /**
     * 设置入口牌识图片
     * 
     * @param enImage
     *          入口牌识图片
     */
    public void setEnImage(String enImage) {
        this.enImage = enImage;
    }

    /**
     * 获取出口车道Node十六进制码
     * 
     * @return 出口车道Node十六进制码
     */
    public String getExLaneHex() {
        return this.exLaneHex;
    }

    /**
     * 设置出口车道Node十六进制码
     * 
     * @param exLaneHex
     *          出口车道Node十六进制码
     */
    public void setExLaneHex(String exLaneHex) {
        this.exLaneHex = exLaneHex;
    }

    /**
     * 获取出口车牌
     * 
     * @return 出口车牌
     */
    public String getExVehPlate() {
        return this.exVehPlate;
    }

    /**
     * 设置出口车牌
     * 
     * @param exVehPlate
     *          出口车牌
     */
    public void setExVehPlate(String exVehPlate) {
        this.exVehPlate = exVehPlate;
    }

    /**
     * 获取出口时间
     * 
     * @return 出口时间
     */
    public Date getExTransTime() {
        return this.exTransTime;
    }

    /**
     * 设置出口时间
     * 
     * @param exTransTime
     *          出口时间
     */
    public void setExTransTime(Date exTransTime) {
        this.exTransTime = exTransTime;
    }

    /**
     * 获取出口通行介质 5 ETC通行，6 CPC卡，9 纸券
     * 
     * @return 出口通行介质 5 ETC通行
     */
    public Integer getExPassType() {
        return this.exPassType;
    }

    /**
     * 设置出口通行介质 5 ETC通行，6 CPC卡，9 纸券
     * 
     * @param exPassType
     *          出口通行介质 5 ETC通行
     */
    public void setExPassType(Integer exPassType) {
        this.exPassType = exPassType;
    }

    /**
     * 获取出口CPC/ETC卡ID
     * 
     * @return 出口CPC/ETC卡ID
     */
    public String getExCardId() {
        return this.exCardId;
    }

    /**
     * 设置出口CPC/ETC卡ID
     * 
     * @param exCardId
     *          出口CPC/ETC卡ID
     */
    public void setExCardId(String exCardId) {
        this.exCardId = exCardId;
    }

    /**
     * 获取出口车情 0-普通  8-军警 10-紧急  14-车队 （35号公告已定义）21-绿通车 22-联合收割机 23-抢险救灾 24-Jl类型集装箱 25-大件运输；26-应急车27-货车列车或半挂汽车列车 28- J2类型集装箱 90-放行车 91-闯关车
     * 
     * @return 出口车情 0-普通  8-军警 10-紧急  14-车队 
     */
    public Integer getExVehStatus() {
        return this.exVehStatus;
    }

    /**
     * 设置出口车情 0-普通  8-军警 10-紧急  14-车队 （35号公告已定义）21-绿通车 22-联合收割机 23-抢险救灾 24-Jl类型集装箱 25-大件运输；26-应急车27-货车列车或半挂汽车列车 28- J2类型集装箱 90-放行车 91-闯关车
     * 
     * @param exVehStatus
     *          出口车情 0-普通  8-军警 10-紧急  14-车队 
     */
    public void setExVehStatus(Integer exVehStatus) {
        this.exVehStatus = exVehStatus;
    }

    /**
     * 获取出口牌识图片
     * 
     * @return 出口牌识图片
     */
    public String getExImage() {
        return this.exImage;
    }

    /**
     * 设置出口牌识图片
     * 
     * @param exImage
     *          出口牌识图片
     */
    public void setExImage(String exImage) {
        this.exImage = exImage;
    }

    /**
     * 获取计费方式 1-按OBU内累计优惠后金额计费   2-按OBU内累计优惠前金额计费（废弃） 3-按CPC卡内累计金额计费  4-省中心在线服务计费5-部中心在线服务计费  6-按全网最小费额计费  11-开放式计费
     * 
     * @return 计费方式 1-按OBU内累计优惠后金额计费   2-按OBU内累计优惠前金额计费
     */
    public BigDecimal getFeeType() {
        return this.feeType;
    }

    /**
     * 设置计费方式 1-按OBU内累计优惠后金额计费   2-按OBU内累计优惠前金额计费（废弃） 3-按CPC卡内累计金额计费  4-省中心在线服务计费5-部中心在线服务计费  6-按全网最小费额计费  11-开放式计费
     * 
     * @param feeType
     *          计费方式 1-按OBU内累计优惠后金额计费   2-按OBU内累计优惠前金额计费
     */
    public void setFeeType(BigDecimal feeType) {
        this.feeType = feeType;
    }

    /**
     * 获取总金额
     * 
     * @return 总金额
     */
    public BigDecimal getTollFee() {
        return this.tollFee;
    }

    /**
     * 设置总金额
     * 
     * @param tollFee
     *          总金额
     */
    public void setTollFee(BigDecimal tollFee) {
        this.tollFee = tollFee;
    }

    /**
     * 获取本省金额
     * 
     * @return 本省金额
     */
    public BigDecimal getLocalFee() {
        return this.localFee;
    }

    /**
     * 设置本省金额
     * 
     * @param localFee
     *          本省金额
     */
    public void setLocalFee(BigDecimal localFee) {
        this.localFee = localFee;
    }

    /**
     * 获取交易金额
     * 
     * @return 交易金额
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * 设置交易金额
     * 
     * @param amount
     *          交易金额
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    public String getEnGid() {
        return enGid;
    }

    public void setEnGid(String enGid) {
        this.enGid = enGid;
    }

    public String getExGid() {
        return exGid;
    }

    public void setExGid(String exGid) {
        this.exGid = exGid;
    }

    public String getPassId() {
        return passId;
    }

    public void setPassId(String passId) {
        this.passId = passId;
    }
}