package com.pingok.datacenter.domain.roster.epidemic;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * 中高风险地区车牌名单表(TBL_PREFIX_LIST_RECORD)
 *
 * @author xia
 * @version 1.0.0 2022-07-20
 */
@Data
@Table(name = "TBL_PREFIX_LIST_RECORD")
public class TblPrefixListRecord implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private Long id;

    /** 车牌前缀 */
    private String prefix;

    private Date startTime;

    /** 版本号 */
    private String version;

    private Date dbTime;
    /**
     * 版本表主键Id
     */
    private Long versionId;
}
