package com.pingok.datacenter.domain.provincialCenters;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * 入口通行记录-省中心(TBL_SHAR_ENPD_RES_SENDER)
 *
 * @author qiumin
 * @version 1.0.0 2023-02-22
 */
@Data
public class TblSharEnpdResSender implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = -5935450598804805195L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * 入口处理编号（id）=入口车道编号+交易批次号+批次内流水号（6 位）
     */
    private String id;

    /**
     * 通行介质类型1 位数字1-OBU 2-CPC 卡3-纸券4-M1 卡9-无通行介
     */
    private BigDecimal mediaType;

    /**
     * OBU 单/双片标识1 位数字1-单片式 OBU 2-双片式 OBU
     */
    private BigDecimal obuSign;

    /**
     * PSAM 卡脱机交易序列号
     */
    private String terminalTransNo;

    /**
     * OBU 序号编码
     */
    private String obuId;

    /**
     * CPC 卡或 ETC卡的编号
     */
    private String cardId;

    /**
     * 入口处理时间
     */
    private Date enTime;

    /**
     * 实际车辆车牌号码+颜色实际车辆车牌号码从 OBU，或 CPC 卡，或 ETC 卡中读出。车牌号码+间隔符+车牌颜色间隔符：“_” 车牌颜色 2 位数字: 0-蓝色，1-黄色，处理成功时必填2-黑色，3-白色，4- 渐变绿色5- 黄绿双拼色6- 蓝白渐变色7- 临时牌照11-绿色12-红色例：京 A12345_1
     */
    private String vehicleId;

    /**
     * 入口识别车辆车牌号码+颜色车牌号码+间隔符+车牌颜色间隔符：“_” 车牌颜色 2 位数字: 0-蓝色，1-黄色，2-黑色，3-白色，4- 渐变绿色5- 黄绿双拼色6- 蓝白渐变色9- 未确定11-绿色12-红色例：京 A12345_1
     */
    private String identifyVehicleId;

    /**
     * 1-一型客车2-二型客车3-三型客车4-四型客车11-一型货车12-二型货车13-三型货车14-四型货车15-五型货车16-六型货车21-一型专项作业车22-二型专项作业车23-三型专项作业车24-四型专项作业车25-五型专项作业车26-六型专项作业车
     */
    private BigDecimal vehicleType;

    /**
     * 车种 0-普通 8-军警 10-紧急 14-车队 （35 号公告已定义）21-绿通车 22-联合收割机 23-抢险救灾 24-Jl 类型集装箱 25-大件运输；26-应急车 27-货车列车或半挂汽车列车 28- J2类型集装箱
     */
    private BigDecimal vehicleClass;

    /**
     * TAC 码 8 位 16 进制数
     */
    private String tac;

    /**
     * 卡面扣费金额 默认为 0，则该字段填写 0，以进行 TAC 验证
     */
    private BigDecimal transFee;

    /**
     * 交易类型标识 PBOC 定义，如 06 为传统交易，09 为复合交易
     */
    private String transType;

    /**
     * 终端机编号 PSAM 中 0016 文件中的终端机编号
     */
    private String terminalNo;

    /**
     * 入口重量
     */
    private String enWeight;

    /**
     * 入口轴数
     */
    private BigDecimal enAxleCount;

    /**
     * 单片式OBU/CPC 卡电量百分比填写 0-100，若无法读数或读数异常时填-1
     */
    private BigDecimal electricalPercentage;

    /**
     * 标记状态1-处理成功2-处理失败
     */
    private BigDecimal signStatus;

    /**
     * 特情类型参见编码规则。多种特情时，以“|”分隔
     */
    private String specialType;

    /**
     * 车牌识别流水号
     */
    private String vehicleSignId;

    /**
     * 入口车道 hex
     */
    private String enTollLaneHex;

    /**
     * 通行标识 ID 车辆通行唯一编号，通行介质为纸卷或无通行介质时可为空：（1）00+0000+OBU 合同序列号+OBU 内入口时间 （2）01+卡网络编号+用户卡号+卡内入口时间示例：否（3）02+0000+CPC 卡编码+入口时间（4）09+0000+M1 卡号（16位）+入口时间
     */
    private String passId;

    /**
     * 车辆识别标识 本字段由收费车道或 ETC 门架填写0x00-大件运输0x01-非优惠车0x02-绿通车0x03-联合收割机车0x04-集装箱车0x05-0xfe 预留0xff 为默认值
     */
    private String vehicleSign;

    /**
     * 车道类型 1-ETC 2-MTC 3-混合（ETC+MTC）4-复式混合（一条车道多个收费亭）5-虚拟（通过便携机收费）
     */
    private BigDecimal laneType;

    /**
     * 作业媒介 1- 车道2- 手持终端
     */
    private BigDecimal operationMedia;

    private String year;

}