package com.pingok.datacenter.domain.provincialCenters;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 门架牌识记录-省中心(TBL_SHAR_GVID_RES_SENDER)
 *
 * @author bianj
 * @version 1.0.0 2023-02-22
 */
@Data
public class TblSharGvidResSender implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = 8409701638858962878L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * 车牌识别流水号（唯一索引）
     */
    private String picId;

    /**
     * 门架编号
     */
    private String gantryId;

    /**
     * ETC 门架 Hex 值
     */
    private String gantryHex;

    /**
     * 抓拍时间
     */
    private Date picTime;

    /**
     * 门架顺序号
     */
    private BigDecimal gantryOrderNum;

    /**
     * 行驶方向
     */
    private BigDecimal driveDir;

    /**
     * 牌识编号
     */
    private BigDecimal cameraNum;

    /**
     * 小时批次号
     */
    private String hourBatchNo;

    /**
     * 拍摄位置  1-车头;2-车尾
     */
    private BigDecimal shootPosition;

    /**
     * 物理车道编码   由行驶方向内侧向外顺序递增，跨多车道时采用组合编号，如：1、2、3、123 等
     */
    private String laneNum;

    /**
     * 识别车牌   车牌号码+间隔符+车牌颜色，间隔符：“_” 车牌颜色 2 位数字: 0-蓝色，1-黄色，2-黑色，3-白色，4- 渐变绿色5- 黄绿双拼色6- 蓝白渐变色9- 未确定11-绿色12-红色例：京 A12345_1，若无法识别车牌，可填写为默A00000_9
     */
    private String vehiclePlate;

    /**
     * 车辆速度  单位：千米/小时
     */
    private BigDecimal vehicleSpeed;

    /**
     * 识别车型
     */
    private BigDecimal identifyType;

    /**
     * 车辆品牌型号
     */
    private String vehicleModel;

    /**
     * 车身颜色
     */
    private String vehicleColor;

    /**
     * 图片大小  单位：B，JPEG 格式
     */
    private BigDecimal imageSize;

    /**
     * 车牌图片大小  单位：B，JPEG 格式
     */
    private BigDecimal licenseImageSize;

    /**
     * 二值化图片大小  单位：B，BMP 格式
     */
    private BigDecimal binImageSize;

    /**
     * 车牌可信度  %，带两位小数
     */
    private String reliability;

    /**
     * 车脸识别特征码和算法版本号
     */
    private String vehFeatureCode;

    /**
     * 人脸特征码和算法版本号
     */
    private String faceFeatureCode;

    /**
     * 校验码  对牌识流水的关键字段组合生成的 CRC 校验码
     */
    private String verifyCode;

    /**
     * 计费交易编号
     */
    private String tradeId;

    /**
     * 匹配状态 0-未处理（默认）；1-有配结果；2-无匹配结果
     */
    private BigDecimal matchStatus;

    /**
     * 去重状态  0-未处理（默认）；1-有效数据；2-无效(重复)数据
     */
    private BigDecimal validStatus;

    /**
     * 处理状态 0-未处理（默认）；1-已处理
     */
    private BigDecimal dealStatus;

    /**
     * 关联图片流水号
     */
    private String relatedPicId;

    /**
     * 全部关联图片流水号
     */
    private String allRelatedPicId;

    /**
     * 门架后台入库时间
     */
    private Date stationDbTime;

    /**
     * 门架后台处理时间
     */
    private Date stationDealTime;

    /**
     * 门架后台去重时间
     */
    private Date stationValidTime;

    /**
     * 门架后台匹配时间
     */
    private Date stationMatchTime;

    private String year;

}