package com.pingok.datacenter.domain.provincialCenters;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 出口 ETC 交易记录-省中心(TBL_SHAR_ETCTD_RES_SENDER)
 *
 * @author bianj
 * @version 1.0.0 2023-02-22
 */
@Data
public class TblSharEtctdResSender implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = -3505226838687796343L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * 出口交易编号  出口交易编号（id）=出口车道编号 + 交易批次号（YYYYMMDDHH）+批次内流水号（6 位）出口车道编号参见编码规则
     */
    private String id;

    /**
     * 通行介质  1 位数字1-OBU 2-CPC 卡3-纸券4-M1 9-无通行介质
     */
    private BigDecimal mediaType;

    /**
     * 介质编码 OBU、CPC 卡、纸券CPC 卡 16 位M1 卡 16 位（省域编号 4 位+自定义 2 位+M1 卡号 10位）无介质通行为 030 纸券，为 01+纸券标识(不超过 20 位)
     */
    private String mediaNo;

    /**
     * 交易支付方式 1 位数字1-出口 ETC 通行2-出口 ETC 刷卡通行
     */
    private BigDecimal transPayType;

    /**
     * 计费方式 1 位数字1-按 OBU 内累计优惠后金额计费2-按 OBU 内累计优惠前金额计费（废弃）3-按 CPC 卡内累计金额计费4-省中心在线服务计费5-部中心在线服务计费6-按全网最小费额计费11-开放式计费
     */
    private BigDecimal exitFeeType;

    /**
     * OBU 单/双片标识 1 位数字1-单片式 OBU 2-双片式 OBU
     */
    private BigDecimal obuSign;

    /**
     * 开票标识  1-现场已开具纸质报销凭证2-现场未开具纸质报销凭证
     */
    private BigDecimal identification;

    /**
     * PSAM 卡脱机交易序列号
     */
    private String terminalTransNo;

    /**
     * ETC 卡编号
     */
    private String cardId;

    /**
     * ETC 卡类别  1 位数字1-储值卡2-记账卡
     */
    private BigDecimal etcCardType;

    /**
     * 出口交易时间
     */
    private Date exTime;

    /**
     * 实际车辆车牌号码+颜色  实际车辆车牌号码从 OBU，或 ETC 卡中读出。车牌号码+间隔符+车牌颜色间隔符：“_” 车牌颜色 2 位数字: 0-蓝色，1-黄色，2-黑色，3-白色，4- 渐变绿色5- 黄绿双拼色6- 蓝白渐变色7- 临时牌照11-绿色12-红色例：京 A12345_1
     */
    private String vehicleId;

    /**
     * 出口识别车辆车牌号码+颜色 车牌号码+间隔符+车牌颜色间隔符：“_” 否车牌颜色 2 位数字: 0-蓝色，1-黄色，2-黑色，3-白色，4- 渐变绿色5- 黄绿双拼色6- 蓝白渐变色9- 未确定11-绿色12-红色例：京 A12345_1
     */
    private String identifyVehicleId;

    /**
     * 车牌识别流水号
     */
    private String vehicleSignId;

    /**
     * 收费车型  1-一型客车2-二型客车3-三型客车4-四型客车11-一型货车12-二型货车13-三型货车14-四型货车15-五型货车16-六型货车21-一型专项作业车22-二型专项作业车23-三型专项作业车24-四型专项作业车25-五型专项作业车26-六型专项作业车
     */
    private BigDecimal vehicleType;

    /**
     * 车种 0- 普 通 8- 军 警 10- 紧急 14-车队 （35 号公告已定义）21-绿通车 22-联合收割机 23-抢险救灾 24-Jl 类型集装箱 25-大件运输；26-应急车 27-货车列车或半挂汽车列车 28- J2 类型集装箱
     */
    private BigDecimal vehicleClass;

    /**
     * TAC 码
     */
    private String tac;

    /**
     * 卡面扣费金额  出口时应等于总交易金额。TAC 验证时使用。
     */
    private BigDecimal transFee;

    /**
     * 交易类型标识 PBOC 定义，如 06 为传统交易，09 为复合交易
     */
    private String transType;

    /**
     * 终端机编号 PSAM 中 0016 文件中的终端机编号
     */
    private String terminalNo;

    /**
     * 卡交易前余额
     */
    private BigDecimal preBalance;

    /**
     * 卡交易后余额
     */
    private BigDecimal postBalance;

    /**
     * 出口重量
     */
    private BigDecimal exWeight;

    /**
     * 轴数
     */
    private BigDecimal axleCount;

    /**
     * 对交易的文字解释
     */
    private String description;

    /**
     * 特情类型  参见编码规则。多种特情时，以“|”分隔
     */
    private String specialType;

    /**
     * 入口车道编号  按照编码规则的收费车道编号规则填写通行介质为 3、9 时 可填写默认入口站编号+0000000
     */
    private String enTollLaneId;

    /**
     * 入口车道 hex 通行介质为 3、9 时 可填写默认 0
     */
    private String enTollLaneHex;

    /**
     * 入口交易发生的时间
     */
    private Date enTime;

    /**
     * 入口车货总重
     */
    private BigDecimal enWeight;

    /**
     * 入口轴数
     */
    private BigDecimal enAxleCount;

    /**
     * 入口收费站名称
     */
    private String enTollStationName;

    /**
     * 出口收费站名称
     */
    private String exTollStationName;

    /**
     * 通行标识 ID 车辆通行唯一编号：（1）00+0000+OBU 合同序列号+OBU 内入口时间 （2）01+卡网络编号+用户卡号+卡内入口时间（3）02+0000+CPC 卡编码+入口时间（4）无通行介质时：030+出口车道编号+出口时间（5）04+0000+纸卷编号+是出口时间（6）09+0000+M1 卡号（16 位）+入口时间
     */
    private String passId;

    /**
     * 车辆状态标识 本字段由收费车道或 ETC门架填写0x00-大件运输0x01-非优惠车0x02-绿通车0x03-联合收割机车0x04-集装箱车0x05-0xfe 预留0xff 为默认值
     */
    private String vehicleSign;

    /**
     * 应收金额   单位：分。应收金额=交易金额+优惠金额+省中心优惠金额 单位：分。应收金额=交易金额+优惠金额+省中心优惠金额
     */
    private BigDecimal payFee;

    /**
     * 总交易金额  用于记账和拆分的金额大于等于 0（单位：分）
     */
    private BigDecimal fee;

    /**
     * 优惠金额
     */
    private BigDecimal discountFee;

    /**
     * 标签无卡次数
     */
    private BigDecimal noCardCount;

    /**
     * 计费总里程数  （单位:米）
     */
    private BigDecimal feeMileage;

    /**
     * 最短路径交易金额 大于等于 0（单位：分）
     */
    private BigDecimal shortFee;

    /**
     * 最短计费里程 （单位：米）
     */
    private BigDecimal shortFeeMileage;

    /**
     * 交易金额占比  当多省时必填总交易金额/全网最小费额交易金额
     */
    private BigDecimal feeRate;

    /**
     * 全网最小费额费率版本号
     */
    private String spcRateVersion;

    /**
     * 用户卡累计交易金额 大于等于 0（单位：分）
     */
    private BigDecimal cardTotalAmount;

    /**
     * OBU 累计优惠前通行费金额 大于等于 0（单位：分）
     */
    private BigDecimal obuTotalAmount;

    /**
     * OBU 累计优惠后通行费金额 大于等于 0（单位：分）
     */
    private BigDecimal obuTotalDiscountAmount;

    /**
     * 本省累计通行费金额大于等于 0（单位：分）
     */
    private BigDecimal obuProvinceFee;

    /**
     * 总交易成功次数
     */
    private BigDecimal totalCount;

    /**
     * 本省交易成功次数
     */
    private BigDecimal provTransCount;

    /**
     * 通行省份个数
     */
    private BigDecimal provinceCount;

    /**
     * 省中心优惠类型 省中心确认是否优惠，及优惠类型有省中心优惠1-绿通2-联合收割机3-J1 类型集装箱4- J2 类型集装箱5-节假日
     */
    private BigDecimal discountType;

    /**
     * 省中心优惠金额
     */
    private BigDecimal provinceDiscountFee;

    /**
     * 省中心优惠前交易金额  省中心有特殊优惠的，省中心优惠前交易金额=应收金额 (payFee)- 优惠金额(discountFee)
     */
    private BigDecimal originFee;

    /**
     * 多条省内交易信息
     */
    private String splitProvince;

    private String year;

}