package com.pingok.datacenter.domain.provincialCenters;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 收费站牌识记录-省中心(TBL_SHAR_SVID_RES_SENDER)
 *
 * @author bianj
 * @version 1.0.0 2023-02-22
 */
@Data
public class TblSharSvidResSender implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = 7982908317033916501L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * 车牌识别流水号 车牌识别流水号=收费车道编号+车牌识别批次号（YYYYMMDDHH）+6 位顺序码
     */
    private String id;

    /**
     * 车道编码
     */
    private String laneNum;

    /**
     * 识别车牌 车牌号码+间隔符+车牌颜色间隔符：“_” 车牌颜色 2 位数字: 0-蓝色，1-黄色，2-黑色，3-白色，4- 渐变绿色5- 黄绿双拼色6- 蓝白渐变色9- 未确定11-绿色12-红色例：京 A12345_1，若无法识别车牌，可填写为默A00000_9
     */
    private String vehicleId;

    /**
     * 识别车牌（车尾）车牌号码+间隔符+车牌颜色间隔符：“_” 车牌颜色 2 位数字: 0-蓝色，1-黄色，2-黑色，3-白色，4- 渐变绿色5- 黄绿双拼色6- 蓝白渐变色9- 未确定11-绿色12-红色例：京 A12345_1，若无法识别车牌，可填写为默
     */
    private String tailVehicleId;

    /**
     * 车辆速度 单位：千米/小时
     */
    private BigDecimal vehSpeed;

    /**
     * 识别车型 1-一型客车2-二型客车3-三型客车4-四型客车11-一型货车12-二型货车13-三型货车14-四型货车15-五型货车16-六型货车21-一型专项作业车22-二型专项作业车23-三型专项作业车24-四型专项作业车25-五型专项作业车26-六型专项作业车
     */
    private BigDecimal identifyType;

    /**
     * 车脸识别特征码和算法版本号
     */
    private String vehFeatureCode;

    /**
     * 人脸特征码和算法版本号
     */
    private String faceFeatureCode;

    /**
     * 抓拍时间
     */
    private Date opTime;

    /**
     * 行驶方向 1 位数字1-上行2-下行
     */
    private BigDecimal direction;

    private String year;
}