package com.pingok.vocational.domain.nameList;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 追缴名单(TBL_AUDIT_DATA)
 * 
 * @author bianj
 * @version 1.0.0 2022-10-21
 */
@Data
@Table(name = "TBL_AUDIT_DATA")
public class TblAuditData implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7265145609053095405L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** transId */
    @Id
    private BigDecimal transId;

    /** 版本号 */
    private String version;

    /** 车辆车牌号码+颜色 */
    private String vehicleId;

    /** 进入黑名单的原因 */
    private String reason;

    /** 欠费金额 */
    private Integer owefee;

    /** 欠费行为次数 */
    private Integer evasionCount;

    /** 关联id */
    private BigDecimal versionId;


}