package com.pingok.vocational.domain.nameList;

import lombok.Data;

import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 中高风险地区名单表(TBL_EPIDEMIC_LIST_RECORD)
 * 
 * @author bianj
 * @version 1.0.0 2022-10-24
 */
@Data
@Table(name = "TBL_EPIDEMIC_LIST_RECORD")
public class TblEpidemicListRecordN {
    /** 版本号 */
    private static final long serialVersionUID = -1416571223708259540L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    private BigDecimal id;

    /** 收费站编码 */
    private String stationId;

    /** 收费站Hex码 */
    private String stationHex;

    /** 收费站名称 */
    private String stationName;

    /** 所在地级市 */
    private String regionName;

    /** 生效时间 */
    private Date startTime;

    /** 版本号 */
    private String version;

    /** 关联id */
    private BigDecimal versionId;

    /** 入库时间 */
    private Date dbTime;


}