package com.pingok.vocational.domain.nameList;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 抢险救灾名单(TBL_EMG_APPEND)
 * 
 * @author bianj
 * @version 1.0.0 2022-10-21
 */
@Data
@Table(name = "TBL_EMG_APPEND")
public class TblEmgAppend implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 260560165027554477L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** transId */
    @Id
    private BigDecimal transId;

    /** 关联id */
    private BigDecimal versionId;

    /** fver */
    private String fver;

    /** id */
    private String id;

    /** dataType */
    private BigDecimal dataType;

    /** appointType */
    private String appointType;

    /** discountInfo */
    private String discountInfo;

    /** handleType */
    private BigDecimal handleType;

    /** checkType */
    private BigDecimal checkType;

    /** appointTime */
    private Date appointTime;

    /** vehicleSign */
    private String vehicleSign;

    /** laneHandle */
    private BigDecimal laneHandle;

    /** vehicleIdentifyType */
    private BigDecimal vehicleIdentifyType;

    /** cardId */
    private String cardId;

    /** vehiclePlateId */
    private String vehiclePlateId;

    /** vehiclePlateColor */
    private Integer vehiclePlateColor;

    /** operation */
    private BigDecimal operation;

    /** discountType */
    private BigDecimal discountType;

    /** discount */
    private Float discount;

    /** discountAmount */
    private BigDecimal discountAmount;

    /** discountQuota */
    private BigDecimal discountQuota;

    /** startTime */
    private Date startTime;

    /** endTime */
    private Date endTime;

    /** provinceIds */
    private String provinceIds;

    /** enStation */
    private String enStation;

    /** exStation */
    private String exStation;

}