package com.pingok.vocational.domain.nameList;

import lombok.Data;

import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 追缴名单信息表历史表(TBL_RECOVERY_LIST_RECORD_LOG)
 * 
 * @author bianj
 * @version 1.0.0 2022-10-31
 */
@Data
@Table(name = "TBL_RECOVERY_LIST_RECORD_LOG")
public class TblRecoveryListRecordLog implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 6609492024807912999L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private BigDecimal id;

    /** 版本号 */
    private String version;

    /** 车牌车辆号码+颜色 */
    private String vehicleId;

    /** 进入黑名单的原因 */
    private String reason;

    /** 欠费金额 */
    private BigDecimal oweFee;

    /** 欠费行为次数 */
    private BigDecimal evasionCount;

    /** 关联id */
    private BigDecimal versionId;

    /** 创建或更新时间 */
    private Date updateTime;

    /** 黑名单类型：1.追缴名单 */
    private BigDecimal type;

    /** 状态：1.进入名单 2.解除名单 */
    private BigDecimal status;

    /** 中心创建日期 */
    private Date creationTime;

}