package com.pingok.vocational.domain.nameList;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 追缴名单版本表(TBL_RECOVERY_STATION_USED)
 * 
 * @author bianj
 * @version 1.0.0 2022-10-21
 */
@Data
@Table(name = "TBL_RECOVERY_STATION_USED")
public class TblRecoveryStationUsed implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 5570761096832732115L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private BigDecimal id;

    /** 收费站hex码 */
    private String stationHex;

    /** 名单版本 */
    private String version;

    /** 创建时间 */
    private Date createTime;

    /** 使用时间 */
    private Date applyTime;


}