package com.pingok.vocational.domain.nameList;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 抢险救灾名单版本表(TBL_RESCUE_STATION_USED)
 * 
 * @author bianj
 * @version 1.0.0 2022-10-21
 */
@Data
@Table(name = "TBL_RESCUE_STATION_USED")
public class TblRescueStationUsed implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -2981212774086976454L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private BigDecimal id;

    /** 收费站hex码 */
    private String stationHex;

    /** 名单版本 */
    private String version;

    /** 创建时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /** 使用时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date applyTime;
}