package com.pingok.vocational.domain.nameList;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 最小费率表(TBL_RATE)
 * 
 * @author bianj
 * @version 1.0.0 2022-10-21
 */
@Data
@Table(name = "TBL_RATE")
public class TblRate implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3387033423400066997L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private BigDecimal id;

    /** 版本号 */
    private String version;

    /** 入口收费站对应省域编码 */
    private String enProv;

    /** 出口收费站对应省域编码 */
    private String exProv;

    /** 入口收费站编码 */
    private String enId;

    /** 出口收费站编码 */
    private String exId;

    /** 车型 */
    private BigDecimal vehClass;

    /** 总金额 */
    private BigDecimal fee;

    /** 95折总实收金额 */
    private BigDecimal fee95;

    /** 总里程数 */
    private BigDecimal m;

    /** 生效时间 */
    private Date effectTime;

    /** 关联id */
    private BigDecimal versionId;

}