package com.pingok.vocational.domain.nameList;

import lombok.Data;

import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * TBL_VERSION_LIST
 * 
 * @author bianj
 * @version 1.0.0 2022-10-21
 */
@Data
@Table(name = "TBL_VERSION_LIST")
public class TblVersionList implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7221942555038172493L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private BigDecimal id;

    /** 版本号 */
    private String version;


}