package com.pingok.vocational.domain.roster;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.Id;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 中高风险地区名单表(TBL_EPIDEMIC_LIST_RECORD)
 * 
 * @author xia
 * @version 1.0.0 2022-07-20
 */
public class TblEpidemicListRecord implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4462453608842553099L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private Long id;

    /** 收费站编码 */
    private String stationId;

    /** 收费站Hex码 */
    private String stationHex;

    /** 收费站名称 */
    private String stationName;

    /** 所在地级市 */
    private String regionName;

    /** 生效时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date startTime;

    /** 版本号 */
    private String version;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取主键
     * 
     * @return 主键
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置主键
     * 
     * @param id
     *          主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取收费站编码
     * 
     * @return 收费站编码
     */
    public String getStationId() {
        return this.stationId;
    }

    /**
     * 设置收费站编码
     * 
     * @param stationId
     *          收费站编码
     */
    public void setStationId(String stationId) {
        this.stationId = stationId;
    }

    /**
     * 获取收费站Hex码
     * 
     * @return 收费站Hex码
     */
    public String getStationHex() {
        return this.stationHex;
    }

    /**
     * 设置收费站Hex码
     * 
     * @param stationHex
     *          收费站Hex码
     */
    public void setStationHex(String stationHex) {
        this.stationHex = stationHex;
    }

    /**
     * 获取收费站名称
     * 
     * @return 收费站名称
     */
    public String getStationName() {
        return this.stationName;
    }

    /**
     * 设置收费站名称
     * 
     * @param stationName
     *          收费站名称
     */
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    /**
     * 获取所在地级市
     * 
     * @return 所在地级市
     */
    public String getRegionName() {
        return this.regionName;
    }

    /**
     * 设置所在地级市
     * 
     * @param regionName
     *          所在地级市
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * 获取生效时间
     * 
     * @return 生效时间
     */
    public Date getStartTime() {
        return this.startTime;
    }

    /**
     * 设置生效时间
     * 
     * @param startTime
     *          生效时间
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * 获取版本号
     * 
     * @return 版本号
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * 设置版本号
     * 
     * @param version
     *          版本号
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}