package com.pingok.vocational.domain.parkingLot;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TBL_EVENT_PASSENGER_FLOW
 * 
 * @author xia
 * @version 1.0.0 2022-06-15
 */
@Data
@Table(name = "TBL_EVENT_PASSENGER_FLOW")
public class TblEventPassengerFlow implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -1605808553120929142L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private Long id;

    /** 客流类型 */
    private Integer uiType;

    /** 开始时间(秒数) 注：间隔开始时间,毫秒 */
    private Long ubiStartTime;

    /** 结束时间(秒数) 注: 间隔结束时间,毫秒 */
    private Long ubiEndTime;

    /** 统计时间间隔,单位秒 */
    private Integer uiCountingInterval;

    /** 视频id */
    private Long ubiSourceId;

    /** 区域id(检测区域编号) */
    private String szAreaId;

    /** 进人数(20秒内进入的人数) */
    private Integer uiGetInPeos;

    /** 出人数(20秒内出去的人数) */
    private Integer uiGetOutPeos;

    /** 在内人数(当前人数) */
    private Integer uiInPeos;

    /** 图片ID */
    private Long ubiImgId;
}