package com.pingok.vocational.domain.parkingLot;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 车流统计表(TBL_PARKING_STATISTICS)
 * 
 * @author xia
 * @version 1.0.0 2022-09-07
 */
public class TblParkingStatistics implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 5459353661272099808L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private BigDecimal id;

    /** 场地id */
    private BigDecimal fieldId;

    /** 1：客车 2：货车 */
    private BigDecimal vehType;

    /** 日期 */
    private Date day;

    /** 小时 */
    private BigDecimal hour;

    /** 当前车辆数量 */
    private BigDecimal current;

    /** 驶入车辆数量 */
    private BigDecimal enter;

    /** 驶出车辆数量 */
    private BigDecimal out;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public BigDecimal getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * 获取场地id
     * 
     * @return 场地id
     */
    public BigDecimal getFieldId() {
        return this.fieldId;
    }

    /**
     * 设置场地id
     * 
     * @param fieldId
     *          场地id
     */
    public void setFieldId(BigDecimal fieldId) {
        this.fieldId = fieldId;
    }

    /**
     * 获取1：客车 2：货车
     * 
     * @return 1：客车 2：货车
     */
    public BigDecimal getVehType() {
        return this.vehType;
    }

    /**
     * 设置1：客车 2：货车
     * 
     * @param vehType
     *          1：客车 2：货车
     */
    public void setVehType(BigDecimal vehType) {
        this.vehType = vehType;
    }

    /**
     * 获取日期
     * 
     * @return 日期
     */
    public Date getDay() {
        return this.day;
    }

    /**
     * 设置日期
     * 
     * @param day
     *          日期
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * 获取小时
     * 
     * @return 小时
     */
    public BigDecimal getHour() {
        return this.hour;
    }

    /**
     * 设置小时
     * 
     * @param hour
     *          小时
     */
    public void setHour(BigDecimal hour) {
        this.hour = hour;
    }

    /**
     * 获取当前车辆数量
     * 
     * @return 当前车辆数量
     */
    public BigDecimal getCurrent() {
        return this.current;
    }

    /**
     * 设置当前车辆数量
     * 
     * @param current
     *          当前车辆数量
     */
    public void setCurrent(BigDecimal current) {
        this.current = current;
    }

    /**
     * 获取驶入车辆数量
     * 
     * @return 驶入车辆数量
     */
    public BigDecimal getEnter() {
        return this.enter;
    }

    /**
     * 设置驶入车辆数量
     * 
     * @param enter
     *          驶入车辆数量
     */
    public void setEnter(BigDecimal enter) {
        this.enter = enter;
    }

    /**
     * 获取驶出车辆数量
     * 
     * @return 驶出车辆数量
     */
    public BigDecimal getOut() {
        return this.out;
    }

    /**
     * 设置驶出车辆数量
     * 
     * @param out
     *          驶出车辆数量
     */
    public void setOut(BigDecimal out) {
        this.out = out;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}