package com.pingok.vocational.domain.parkingLot;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * 停车场出入车辆信息表(TBL_PARKING_VEHICLE_INFO)
 * 
 * @author qiumin
 * @version 1.0.0 2022-04-08
 */
@Data
@Table(name = "TBL_PARKING_VEHICLE_INFO")
public class TblParkingVehicleInfo implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7132345013553295596L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private Long id;

    /** 入口时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date enTime;

    /** 出口时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date exTime;

    /** 车牌 */
    private String vehPlate;

    /** 车型 */
    private Integer vehClass;

    /** 车型 */
    private Integer vehClassSub;

    /** 车牌颜色 */
    private Integer vehColor;

    /** 停车区域id */
    private Long parkingId;

    /** 创建时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /** 更新时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /** 创建用户ID */
    private Long createUserId;

    /** 更新用户ID */
    private Long updateUserId;

    private Integer status;

}