package com.pingok.vocational.domain.parkingLot;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.ruoyi.common.core.annotation.Excel;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 人员健康信息表(TBL_PERSONNEL_HEALTH)
 * 
 * @author xia
 * @version 1.0.0 2022-09-21
 */
@Data
@Table(name = "TBL_PERSONNEL_HEALTH")
public class TblPersonnelHealth implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3834991549370655602L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private Long id;

    /** 姓名 */
    private String name;

    /** 区域 */
    private Long fieldId;

    /** 日期 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date transDate;

    /** 核酸(小时) */
    private Integer nucleicAcid;

    /** 体温 */
    private Integer temperature;

    /** 创建时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /** 更新时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /** 创建用户ID */
    private Long createUserId;

    /** 更新用户ID */
    private Long updateUserId;
}