package com.pingok.gis.domain;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * road
 * 
 * @author bianj
 * @version 1.0.0 2023-03-05
 */
@Data
@Table(name = "road")
public class Road implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1123538632913427684L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** gid */
    @Id
    private Integer gid;

    /** id */
    private Integer id;

    /** code */
    private String code;

    /** type */
    private String type;

    /** status */
    private Integer status;

    /** direction */
    private Integer direction;

    /** name */
    private String name;

    /** category */
    private Integer category;

    /** geom */
    private String geom;

    /** mileage */
    private String mileage;

    /** flow */
    private Integer flow;

}