package com.pingok.gis.domain;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * road_g60_water_polygon_md_splitbyg
 * 
 * @author bianj
 * @version 1.0.0 2023-03-05
 */
@Data
@Table(name = "road_g60_water_polygon_md_splitbyg")
public class RoadG60WaterPolygonMdSplitbyg {
    /** 版本号 */
    private static final long serialVersionUID = 3047505958327672939L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** gid */
    @Id
    private Integer gid;

    /** id */
    private Integer id;

    /** code */
    private String code;

    /** type */
    private String type;

    /** status */
    private Integer status;

    /** direction */
    private Integer direction;

    /** name */
    private String name;

    /** category */
    private Integer category;

    /** geom */
    private String geom;

    /** startPoint */
    private String startPoint;

    /** endPoint */
    private String endPoint;

}