package com.pingok.datacenter.domain.software;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 软件信息表(TBL_SOFTWARE_INFO)
 * 
 * @author qiumin
 * @version 1.0.0 2022-03-24
 */
@Table(name = "TBL_SOFTWARE_INFO")
public class TblSoftwareInfo  implements Serializable {

    /** id */
    @Id
    private Long id;

    /** 软件编码 */
    private String num;

    /** 软件名称 */
    private String name;

    /** 版本号 */
    private String version;

    /** ip */
    private String ip;

    /** 心跳时间 */
    private Date time;

    /** 运行状态：1-正常 0-异常 */
    private Integer status;

    /** 状态描述 */
    private String statusCode;

    /** 上传标志位：1-有上传业务 0-无上传业务 */
    private Integer uploadFlag;

    /** 上传状态数组 */
    private String uploadStatus;

    /** 下载标志位：1-有下载业务 0-无下载业务 */
    private Integer downloadFlag;

    /** 下载状态数组 */
    private String downloadStatus;

    /** 创建时间 */
    private Date createTime;

    /** 更新时间 */
    private Date updateTime;

    /** 创建用户ID */
    private BigDecimal createUserId;

    /** 更新用户ID */
    private BigDecimal updateUserId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取软件编码
     * 
     * @return 软件编码
     */
    public String getNum() {
        return this.num;
    }

    /**
     * 设置软件编码
     * 
     * @param num
     *          软件编码
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * 获取软件名称
     * 
     * @return 软件名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置软件名称
     * 
     * @param name
     *          软件名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取版本号
     * 
     * @return 版本号
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * 设置版本号
     * 
     * @param version
     *          版本号
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * 获取ip
     * 
     * @return ip
     */
    public String getIp() {
        return this.ip;
    }

    /**
     * 设置ip
     * 
     * @param ip
     *          ip
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * 获取心跳时间
     * 
     * @return 心跳时间
     */
    public Date getTime() {
        return this.time;
    }

    /**
     * 设置心跳时间
     * 
     * @param time
     *          心跳时间
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * 获取运行状态：1-正常 0-异常
     * 
     * @return 运行状态
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * 设置运行状态：1-正常 0-异常
     * 
     * @param status
     *          运行状态
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取状态描述
     * 
     * @return 状态描述
     */
    public String getStatusCode() {
        return this.statusCode;
    }

    /**
     * 设置状态描述
     * 
     * @param statusCode
     *          状态描述
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * 获取上传标志位：1-有上传业务 0-无上传业务
     * 
     * @return 上传标志位
     */
    public Integer getUploadFlag() {
        return this.uploadFlag;
    }

    /**
     * 设置上传标志位：1-有上传业务 0-无上传业务
     * 
     * @param uploadFlag
     *          上传标志位
     */
    public void setUploadFlag(Integer uploadFlag) {
        this.uploadFlag = uploadFlag;
    }

    /**
     * 获取上传状态数组
     * 
     * @return 上传状态数组
     */
    public String getUploadStatus() {
        return this.uploadStatus;
    }

    /**
     * 设置上传状态数组
     * 
     * @param uploadStatus
     *          上传状态数组
     */
    public void setUploadStatus(String uploadStatus) {
        this.uploadStatus = uploadStatus;
    }

    /**
     * 获取下载标志位：1-有下载业务 0-无下载业务
     * 
     * @return 下载标志位
     */
    public Integer getDownloadFlag() {
        return this.downloadFlag;
    }

    /**
     * 设置下载标志位：1-有下载业务 0-无下载业务
     * 
     * @param downloadFlag
     *          下载标志位
     */
    public void setDownloadFlag(Integer downloadFlag) {
        this.downloadFlag = downloadFlag;
    }

    /**
     * 获取下载状态数组
     * 
     * @return 下载状态数组
     */
    public String getDownloadStatus() {
        return this.downloadStatus;
    }

    /**
     * 设置下载状态数组
     * 
     * @param downloadStatus
     *          下载状态数组
     */
    public void setDownloadStatus(String downloadStatus) {
        this.downloadStatus = downloadStatus;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取更新时间
     * 
     * @return 更新时间
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置更新时间
     * 
     * @param updateTime
     *          更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取创建用户ID
     * 
     * @return 创建用户ID
     */
    public BigDecimal getCreateUserId() {
        return this.createUserId;
    }

    /**
     * 设置创建用户ID
     * 
     * @param createUserId
     *          创建用户ID
     */
    public void setCreateUserId(BigDecimal createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * 获取更新用户ID
     * 
     * @return 更新用户ID
     */
    public BigDecimal getUpdateUserId() {
        return this.updateUserId;
    }

    /**
     * 设置更新用户ID
     * 
     * @param updateUserId
     *          更新用户ID
     */
    public void setUpdateUserId(BigDecimal updateUserId) {
        this.updateUserId = updateUserId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */


}