package com.pingok.event.domain.videoEvent;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.springframework.data.annotation.Id;

import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * 服务区客流统计表(TBL_EVENT_PASSENGER_STATISTICS)
 *
 * @author bianj
 * @version 1.0.0 2022-09-29
 */
@Data
@Table(name = "TBL_EVENT_PASSENGER_STATISTICS")
public class TblEventPassengerStatistics implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = -2241602963129877750L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * 主键
     */
    @Id
    private Long id;

    /**
     * 日期  yyyy-mm-dd
     */
    @ApiModelProperty(value = "日期  yyyy-mm-dd")
    private Date workDate;

    /**
     * 小时
     */
    @ApiModelProperty(value = "小时")
    private Integer hour;

    /**
     * 区域id。1.北服务区商铺；2.北服务区小超市；3.北服务区男厕；4.北服务区女厕；5.南服务区商铺；6.南服务区艺海棠；7.南服务区超市；8.南服务区男厕；9.南服务区女厕；10.南服务区司机之家
     */
    @ApiModelProperty(value = "区域id。1.北服务区商铺；2.北服务区小超市；3.北服务区男厕；4.北服务区女厕；5.南服务区商铺；6.南服务区艺海棠；7.南服务区超市；8.南服务区男厕；9.南服务区女厕；10.南服务区司机之家")
    private Integer areaId;

    /**
     * 进人数
     */
    @ApiModelProperty(value = "进人数")
    private Integer entry;

    /**
     * 出人数
     */
    @ApiModelProperty(value = "出人数")
    private Integer out;

    /**
     * 在内人数(当前人数)
     */
    @ApiModelProperty(value = "在内人数(当前人数)")
    private Integer inAmount;

    /**
     * 服务区ID
     */
    @ApiModelProperty(value = "服务区ID")
    private Long fieldId;

}