package com.pingok.event.domain.videoEvent;

import lombok.Data;

import javax.persistence.Table;
import java.math.BigDecimal;

/**
 * 人像信息详情表(TBL_FACE_INFO_DETAIL)
 * 
 * @author bianj
 * @version 1.0.0 2023-04-23
 */
@Data
@Table(name = "TBL_FACE_INFO_DETAIL")
public class TblFaceInfoDetail {
    /** 版本号 */
    private static final long serialVersionUID = -1418484365221154282L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** ubiLogicId */
    private Long ubiLogicId;

    /** 检测时间 */
    private Long ubiTime;

    /** 相机ID */
    private Long ubiSourceId;

    /** 相机编号 */
    private String szSourceCode;

    /** 年龄段 */
    private Integer uiAge;

    /** 性别，0=男，1=女 */
    private Integer uiSex;

    /** 口罩，0=戴口罩，1=没戴口罩 */
    private Integer uiMask;

    /** 图片Base64，大图 */
    private String szImg;

}