package com.pingok.event.domain.videoEvent;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 停车场出入车辆信息表(TBL_PARKING_VEHICLE_INFO)
 * 
 * @author xia
 * @version 1.0.0 2022-06-15
 */
@Data
@Table(name = "TBL_PARKING_VEHICLE_INFO")
public class TblParkingVehicleInfo implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7101783917167922508L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private Long id;

    /** 入口时间 */
    private Date enTime;

    /** 出口时间 */
    private Date exTime;

    /** 车牌 */
    private String vehPlate;

    /** 车型 */
    private Integer vehClass;

    /** 车牌颜色 */
    private Integer vehColor;

    /** 停车区域id */
    private Long parkingId;

    /** 创建时间 */
    private Date createTime;

    /** 更新时间 */
    private Date updateTime;

    /** 创建用户ID */
    private Long createUserId;

    /** 更新用户ID */
    private Long updateUserId;

    /** 车型细分 */
    private Integer vehClassSub;

    private Integer status;
}