package com.pingok.datacenter.domain.blackcard;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 状态名单信息表(TBL_BLACK_CARD)
 *
 * @author bianj
 * @version 1.0.0 2022-09-13
 */
@Table(name = "TBL_BLACK_CARD")
@Data
public class TblBlackCard implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = -6658548940797159780L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * 主键
     */
    @Id
    private Long id;

    /**
     * 媒介id：obu或cpc id
     */
    @ApiModelProperty(value = "媒介id：obu或cpc id")
    private String mediaId;

    /**
     * 发行服务机构编码
     */
    @ApiModelProperty(value = "发行服务机构编码")
    private String issuerId;

    /**
     * 部联网中心入库时间
     */
    @ApiModelProperty(value = "部联网中心入库时间")
    private Date insertTime;

    /**
     * 状态类型:1位数字1-卡挂失2-无卡挂起3-无卡注销4-账户透支5-合作机构黑名单6-车型不符储值卡余额不足
     */
    @ApiModelProperty(value = "状态类型:1位数字1-卡挂失2-无卡挂起3-无卡注销4-账户透支5-合作机构黑名单6-车型不符储值卡余额不足")
    private Integer type;

    /**
     * 1位数字1-进入状态名单2-解除状态名单
     */
    @ApiModelProperty(value = "1位数字1-进入状态名单2-解除状态名单")
    private Integer status;

    /**
     * 名单生成时间
     */
    @ApiModelProperty(value = "名单生成时间")
    private Date creationTime;

    /**
     * 版本号
     */
    @ApiModelProperty(value = "版本号")
    private String version;

    /**
     * 创建或更新时间
     */
    @ApiModelProperty(value = "创建或更新时间")
    private Date updateTime;

    /**
     * 媒介类型：1-obu；2-cpc
     */
    @ApiModelProperty(value = "媒介类型：1-obu；2-cpc")
    private Integer mediaType;

    /**
     * 名单启用时间
     */
    @ApiModelProperty(value = "名单启用时间")
    private Date applyTime;

}