package com.pingok.datacenter.domain.roster;

import lombok.Data;

import javax.persistence.Id;
import java.util.Date;

/**
 * 中高风险地区车牌名单表(TBL_EPIDEMIC_PREFIX)
 *
 * @author xia
 * @version 1.0.0 2022-07-20
 */
@Data
public class TblEpidemicPrefix implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 主键 */
    @Id
    private Long id;

    private String prefix;

    private Date startTime;
    /** 版本号 */
    private String version;

    private Date dbTime;

}
