package com.ruoyi.system.api.domain.gps;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * 养护车辆GPS信息表(TBL_MAINTAIN_CAR_GPS)
 * 
 * @author qiumin
 * @version 1.0.0 2022-05-24
 */
@Data
@Table(name = "TBL_MAINTAIN_CAR_GPS")
public class TblMaintainCarGps implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8648977413620825742L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    private Long id;

    /** 车牌 */
    private String licensePlate;

    /** 坐标 */
    private String coordinates;

    /** 时间 */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date time;

    /** 位置描述 */
    private String reverseGeocode;

    /** 车速 */
    private Integer speed;

    /**
     * 创建时间
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * 更新时间
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

}