package com.pingok.algorithmBeiJing.domain;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * 统计事件信息表(TBL_ROAD_STATIS_EVENT_INFO)
 *
 * @author bianj
 * @version 1.0.0 2023-03-09
 */
@Data
@Table(name = "TBL_ROAD_STATIS_EVENT_INFO")
public class TblRoadStatisEventInfo implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = 3438508001930634201L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * id
     */
    @Id
    private Long id;

    /**
     * 事件类型代号
     */
    private Integer type;

    /**
     * 事件描述信息
     */
    private String message;

    /**
     * 路段名称
     */
    private String roadId;

    /**
     * 拥堵等级
     */
    private Integer congestion;

    /**
     * 超速车牌号
     */
    private String exceedCar;

    /**
     * 是否为预测事件,true表示预测事件，false表示历史或实时事件
     */
    private String prediction;

    /**
     * 事件开始时间
     */
    private Date startTime;

    /**
     * 事件结束时间
     */
    private Date endTime;

}