package com.pingok.algorithmBeiJing.domain;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 视频事件信息表(TBL_ROAD_VIDEO_EVENT_INFO)
 *
 * @author bianj
 * @version 1.0.0 2023-03-09
 */
@Data
@Table(name = "TBL_ROAD_VIDEO_EVENT_INFO")
public class TblRoadVideoEventInfo implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = 1345681255307110651L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * id
     */
    @Id
    private Long id;

    /**
     * 摄像头id
     */
    private Long cameraId;

    /**
     * 类型码
     */
    private Integer type;

    /**
     * 异常描述信息
     */
    private String warning;

    /**
     * 车道信息
     */
    private String track;

}