package com.pingok.algorithmBeiJing.domain;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 路段信息表(TBL_ROAD_INFO)
 * 
 * @author bianj
 * @version 1.0.0 2023-03-01
 */
@Data
@Table(name = "TBL_ROAD_INFO")
public class TblRoadInfo implements Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7807804770537705418L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 路段编号 */
    @Id
    private String roadId;

    /** 起始门架编号 */
    private String origin;

    /** 终止门架编号 */
    private String destination;

    /** 路段长度 */
    private BigDecimal length;

    /** 路段描述 */
    private String message;

}