package com.pingok.algorithmBeiJing.domain;

import com.alibaba.fastjson.JSONArray;
import com.ruoyi.common.core.utils.StringUtils;
import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 路段节点信息表(TBL_ROAD_NODES_INFO)
 *
 * @author bianj
 * @version 1.0.0 2023-03-01
 */
@Data
@Table(name = "TBL_ROAD_NODES_INFO")
public class TblRoadNodesInfo implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = -5982241013288056307L;

    /* This code was generated by TableGo tools, mark 1 begin. */


    /**
     * 设备编号
     */
    @Id
    private String id;

    /**
     * 名称
     */
    private String name;

    /**
     * 坐标
     */
    private String geoStr;

    /**
     * 桩号
     */
    private String pileNo;

    /**
     * 方向：1.上行 2.下行
     */
    private BigDecimal direction;

    /**
     * HEX
     */
    private String HEX;

    @Transient
    private JSONArray geo;

}