package com.pingok.algorithmBeiJing.domain;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 单位收益碳排放(TBL_ROAD_CO2_PER_PROFIT)
 *
 * @author bianj
 * @version 1.0.0 2023-03-13
 */
@Data
@Table(name = "TBL_ROAD_CO2_PER_PROFIT")
public class TblRoadCo2PerProfit implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = -1386103240431122947L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * id
     */
    @Id
    private Long id;

    /**
     * 单位收益碳排放
     */
    private BigDecimal co2PerProfit;

    /**
     * 小时增长率
     */
    private BigDecimal incrementPerHour;

    /**
     * 日期
     */
    private Date time;

}