package com.pingok.algorithmBeiJing.domain;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 收益预测表(TBL_ROAD_PROFIT_PRED)
 *
 * @author bianj
 * @version 1.0.0 2023-03-13
 */
@Data
@Table(name = "TBL_ROAD_PROFIT_PRED")
public class TblRoadProfitPred implements Serializable {
    /**
     * 版本号
     */
    private static final long serialVersionUID = -4220606346853213750L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**
     * id
     */
    @Id
    private Long id;

    /**
     * 预测日期
     */
    private Date predDate;

    /**
     * 预测流量
     */
    private BigDecimal predFlow;

    /**
     * 预测收益
     */
    private BigDecimal predProfit;

}